import '@/styles/style.scss'
import '@/scripts/components/ColorScheme/ColorScheme.js'
import '@/scripts/components/modal/modal.js'
import '@/scripts/components/header.js'
import '@/scripts/components/main/slider.js'
import '@/scripts/components/main/catalog.js'
import '@/scripts/components/main/gallery.js'
import '@/scripts/components/main/order.js'
import '@/scripts/components/main.js'
import '@/scripts/components/footer.js'

import '@/images/svg/VintalLife.png'
import '@/images/svg/moon.svg'
import '@/images/svg/burgerlg.svg'
import '@/images/svg/burgerbg.svg'
import '@/images/svg/Logolg.svg'
import '@/images/svg/Logobg.svg'
import '@/images/Footer/logo.jpg'
import '@/images/Header/right.jpg'

import '@/images/BG/bg1.png'
import '@/images/BG/lg1.png'

import '@/images/Header/left.png'

import '@/images/Main/0.png'
import '@/images/Main/1.png'
import '@/images/Main/2.png'
import '@/images/Main/3.jpg'
import '@/images/Main/4.png'
import '@/images/Main/5.png'
import '@/images/Main/6.png'
import '@/images/Main/7.png'
import '@/images/Main/8.png'
import '@/images/Main/9.png'

import '@/images/Main/Logo/l1.png'
import '@/images/Main/Logo/l2.png'
import '@/images/Main/Logo/l3.png'
import '@/images/Main/Logo/l4.png'
import '@/images/Main/Logo/l5.png'
import '@/images/Main/Logo/l6.png'

import '@/images/Main/Logo/b1.png'
import '@/images/Main/Logo/b2.png'
import '@/images/Main/Logo/b3.png'
import '@/images/Main/Logo/b4.png'
import '@/images/Main/Logo/b5.png'
import '@/images/Main/Logo/b6.png'

import '@/images/Main/kitchen/kitchen-1.jpg'
import '@/images/Main/kitchen/kitchen-2.jpg'
import '@/images/Main/kitchen/kitchen-3.jpg'
import '@/images/Main/kitchen/kitchen-4.jpg'
import '@/images/Main/kitchen/kitchen-5.jpg'
import '@/images/Main/kitchen/kitchen-6.jpg'
import '@/images/Main/kitchen/kitchen-7.jpeg'
import '@/images/Main/kitchen/kitchen-8.jpg'
import '@/images/Main/kitchen/kitchen-9.jpg'
import '@/images/Main/kitchen/kitchen-10.jpg'
import '@/images/Main/kitchen/kitchen-11.jpg'
import '@/images/Main/kitchen/kitchen-12.jpg'




